data:extend({
	{
		type = "string-setting",
		name = "smallspage-mode",
		setting_type = "startup",
		default_value = "hyperbolic",
		allowed_values = { "hyperbolic", "spherical" },
		order = "a",
	},
	{
		type = "double-setting",
		name = "smallspage-radius",
		setting_type = "startup",
		default_value = 300,
		minimum_value = 20,
		maximum_value = 100000,
		order = "b",
	},
	{
		type = "bool-setting",
		name = "smallspage-indestructible-enemy-bases",
		setting_type = "runtime-global",
		default_value = false,
		order = "c",
	},
	{
		type = "double-setting",
		name = "smallspage-indestructible-enemy-bases-radius",
		setting_type = "runtime-global",
		default_value = 160,
		minimum_value = 0,
		maximum_value = 100000,
		order = "d",
	},
})
