data:extend({
	{
		type = "string-setting",
		name = "smallspage-mode",
		setting_type = "startup",
		default_value = "hyperbolic",
		allowed_values = { "hyperbolic", "spherical" },
		order = "a",
	},
	{
		type = "double-setting",
		name = "smallspage-radius",
		setting_type = "startup",
		default_value = 500,
		minimum_value = 20,
		maximum_value = 100000,
		order = "b",
	},
	{
		type = "double-setting",
		name = "smallspage-radius-nauvis",
		setting_type = "startup",
		default_value = 600,
		minimum_value = 200,
		maximum_value = 100000,
		order = "c1",
	},
	{
		type = "double-setting",
		name = "smallspage-radius-vulcanus",
		setting_type = "startup",
		default_value = 800,
		minimum_value = 200,
		maximum_value = 100000,
		order = "c2",
	},
	{
		type = "double-setting",
		name = "smallspage-radius-fulgora",
		setting_type = "startup",
		default_value = 450,
		minimum_value = 200,
		maximum_value = 100000,
		order = "c3",
	},
	{
		type = "double-setting",
		name = "smallspage-radius-gleba",
		setting_type = "startup",
		default_value = 350,
		minimum_value = 200,
		maximum_value = 100000,
		order = "c4",
	},
	{
		type = "double-setting",
		name = "smallspage-radius-aquilo",
		setting_type = "startup",
		default_value = 250,
		minimum_value = 200,
		maximum_value = 100000,
		order = "c5",
	},
	{
		type = "bool-setting",
		name = "smallspage-indestructible-enemy-bases",
		setting_type = "runtime-global",
		default_value = false,
		order = "x1",
	},
	{
		type = "double-setting",
		name = "smallspage-indestructible-enemy-bases-radius",
		setting_type = "runtime-global",
		default_value = 160,
		minimum_value = 0,
		maximum_value = 100000,
		order = "x2",
	},
	{
		type = "bool-setting",
		name = "smallspage-auto-scan-planets",
		setting_type = "runtime-global",
		default_value = false,
		order = "y",
	},
})
